/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_vandertil_jerasure_jni_Cauchy */

#ifndef _Included_eu_vandertil_jerasure_jni_Cauchy
#define _Included_eu_vandertil_jerasure_jni_Cauchy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_vandertil_jerasure_jni_Cauchy
 * Method:    cauchy_original_coding_matrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Cauchy_cauchy_1original_1coding_1matrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_Cauchy
 * Method:    cauchy_xy_coding_matrix
 * Signature: (III[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Cauchy_cauchy_1xy_1coding_1matrix
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     eu_vandertil_jerasure_jni_Cauchy
 * Method:    cauchy_improve_coding_matrix
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_eu_vandertil_jerasure_jni_Cauchy_cauchy_1improve_1coding_1matrix
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     eu_vandertil_jerasure_jni_Cauchy
 * Method:    cauchy_good_general_coding_matrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Cauchy_cauchy_1good_1general_1coding_1matrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_Cauchy
 * Method:    cauchy_n_ones
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_eu_vandertil_jerasure_jni_Cauchy_cauchy_1n_1ones
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
