/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_vandertil_jerasure_jni_Liberation */

#ifndef _Included_eu_vandertil_jerasure_jni_Liberation
#define _Included_eu_vandertil_jerasure_jni_Liberation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_vandertil_jerasure_jni_Liberation
 * Method:    liberation_coding_bitmatrix
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Liberation_liberation_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_Liberation
 * Method:    liber8tion_coding_bitmatrix
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Liberation_liber8tion_1coding_1bitmatrix
  (JNIEnv *, jclass, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_Liberation
 * Method:    blaum_roth_coding_bitmatrix
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_Liberation_blaum_1roth_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
