/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_vandertil_jerasure_jni_ReedSolomon */

#ifndef _Included_eu_vandertil_jerasure_jni_ReedSolomon
#define _Included_eu_vandertil_jerasure_jni_ReedSolomon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_vandermonde_coding_matrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1vandermonde_1coding_1matrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_extended_vandermonde_matrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1extended_1vandermonde_1matrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_big_vandermonde_distribution_matrix
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1big_1vandermonde_1distribution_1matrix
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_r6_encode
 * Signature: (II[[B[[BI)I
 */
JNIEXPORT jboolean JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1r6_1encode
  (JNIEnv *, jclass, jint, jint, jobjectArray, jobjectArray, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_r6_coding_matrix
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1r6_1coding_1matrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_galois_w08_region_multby_2
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1galois_1w08_1region_1multby_12
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_galois_w16_region_multby_2
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1galois_1w16_1region_1multby_12
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     eu_vandertil_jerasure_jni_ReedSolomon
 * Method:    reed_sol_galois_w32_region_multby_2
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_eu_vandertil_jerasure_jni_ReedSolomon_reed_1sol_1galois_1w32_1region_1multby_12
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
